# Generated by Django 3.2.19 on 2023-08-10 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230810_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингридиента 1'), django.core.validators.MaxValueValidator(32000, message='Максимально время 32000 минут')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время 1 минута'), django.core.validators.MaxValueValidator(32000, message='Максимально время 32000 минут')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='cart',
            order_with_respect_to='model_to_subscribe',
        ),
        migrations.AlterOrderWithRespectTo(
            name='favorite',
            order_with_respect_to='model_to_subscribe',
        ),
        migrations.AlterOrderWithRespectTo(
            name='ingredientamount',
            order_with_respect_to='ingredient',
        ),
    ]
