# Generated by Django 3.2.19 on 2023-08-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230810_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ['id'], 'verbose_name': 'Количество ингридиента', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='ingredientamount',
            order_with_respect_to=None,
        ),
    ]
