# Generated by Django 3.2.19 on 2023-08-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230811_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='model_to_subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='api.recipe'),
        ),
    ]
