# Generated by Django 3.2.19 on 2023-07-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230701_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
